### ISSUE TITLE
Error Occurred with LimboAuth Plugin during Server Startup: ClassNotFoundException for org.sqlite.JDBC

### ISSUE THREAD

**Issue by adnogpu** [Elytrium/LimboAuth#107]
Hello, my server is using your LimboAuth plugin, and I haven't encountered any issues before. Today, I updated it to the latest version, 1.1.13. However, when I start the server, it displays the following error:

**[20:00:30 ERROR]: Couldn't pass ProxyInitializeEvent to limboauth
net.elytrium.commons.utils.reflection.ReflectionException: An unexpected internal error was caught during the reflection operations.
        at net.elytrium.limboauth.LimboAuth.reload(LimboAuth.java:310) ~[?:?]
        at net.elytrium.limboauth.LimboAuth.onProxyInitialization(LimboAuth.java:208) ~[?:?]
        at net.elytrium.limboauth.Lmbda$3.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.2.0-SNAPSHOT-260.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity-3.2.0-SNAPSHOT-260.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity-3.2.0-SNAPSHOT-260.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: org.sqlite.JDBC
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87) ~[velocity-3.2.0-SNAPSHOT-260.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[velocity-3.2.0-SNAPSHOT-260.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.lambda$static$10(DatabaseLibrary.java:89) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.connect(DatabaseLibrary.java:115) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.connectToORM(DatabaseLibrary.java:131) ~[?:?]
        at net.elytrium.limboauth.LimboAuth.reload(LimboAuth.java:302) ~[?:?]
        ... 8 more**

I am only using the LimboAuth and LimboAPI plugins, and both of them are up to date. can you help me?

**Comment by hevav** [comment]
Send the full log file

**Comment by adnogpu** [comment]
WARN StatusConsoleListener Advanced terminal features are not available in this environment
[21:03:57 INFO]: Booting up Velocity 3.2.0-SNAPSHOT (git-37fedf50-b260)...
[21:03:57 INFO]: Loading localizations...
[21:03:57 INFO]: Connections will use NIO channels, Java compression, Java ciphers
[21:03:57 WARN]: The proxy is running in offline mode! This is a security risk and you will NOT receive any support!
[21:03:57 INFO]: Loading plugins...
[21:03:58 INFO] [limboapi]: Initializing Simple Virtual World system...
[21:03:58 INFO] [limboapi]: Hooking into EventManager, PlayerList/UpsertPlayerInfo and StateRegistry...
[21:03:58 INFO]: Loaded plugin limboapi 1.1.16 by Elytrium (https://elytrium.net/)
[21:03:58 INFO]: Loaded plugin limboauth 1.1.13 by Elytrium (https://elytrium.net/)
[21:03:58 INFO]: Loaded 2 plugins
[21:03:58 INFO] [limboapi]: Creating and preparing packets...
[21:03:58 INFO] [limboapi]: Loaded!
[21:03:59 ERROR]: Couldn't pass ProxyInitializeEvent to limboauth
net.elytrium.commons.utils.reflection.ReflectionException: An unexpected internal error was caught during the reflection operations.
        at net.elytrium.limboauth.LimboAuth.reload(LimboAuth.java:310) ~[?:?]
        at net.elytrium.limboauth.LimboAuth.onProxyInitialization(LimboAuth.java:208) ~[?:?]
        at net.elytrium.limboauth.Lmbda$3.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.2.0-SNAPSHOT-260.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity-3.2.0-SNAPSHOT-260.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity-3.2.0-SNAPSHOT-260.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: org.sqlite.JDBC
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87) ~[velocity-3.2.0-SNAPSHOT-260.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[velocity-3.2.0-SNAPSHOT-260.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.lambda$static$10(DatabaseLibrary.java:89) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.connect(DatabaseLibrary.java:115) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.connectToORM(DatabaseLibrary.java:131) ~[?:?]
        at net.elytrium.limboauth.LimboAuth.reload(LimboAuth.java:302) ~[?:?]
        ... 8 more
[21:03:59 INFO]: Listening on /[0:0:0:0:0:0:0:0]:26009
[21:03:59 INFO]: Done (2.82s)!

**Comment by adnogpu** [comment]
@hevav

**Comment by adnogpu** [comment]
@JNNGL
