### ISSUE TITLE
[BUG] Cannot connect to Mysql

### ISSUE THREAD

**Issue by BigCookie233** [Elytrium/LimboAuth#123]
**Describe the bug**
The latest LimboAuth cannot connect to Mysql. And LimboAuth 1.1.11 doesn't have the bug.

**To Reproduce**
1. Configure LimboAuth to use Mysql
2. See error

**Server Info:**
 - LimboAPI 1.1.16
 - LimboAuth 1.1.13

**Additional context**
```
[19:20:47 ERROR]: Couldn't pass ProxyInitializeEvent to limboauth
net.elytrium.commons.utils.reflection.ReflectionException: An unexpected internal error was caught during the reflection operations.
        at net.elytrium.limboauth.LimboAuth.reload(LimboAuth.java:310) ~[?:?]
        at net.elytrium.limboauth.LimboAuth.onProxyInitialization(LimboAuth.java:208) ~[?:?]
        at net.elytrium.limboauth.Lmbda$3.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.2.0-SNAPSHOT-265.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity-3.2.0-SNAPSHOT-265.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity-3.2.0-SNAPSHOT-265.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: com.mysql.cj.jdbc.NonRegisteringDriver
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87) ~[velocity-3.2.0-SNAPSHOT-265.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[velocity-3.2.0-SNAPSHOT-265.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.lambda$static$4(DatabaseLibrary.java:71) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.connect(DatabaseLibrary.java:115) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.connectToORM(DatabaseLibrary.java:131) ~[?:?]
        at net.elytrium.limboauth.LimboAuth.reload(LimboAuth.java:302) ~[?:?]
        ... 8 more
```

**Comment by mdxd44** [comment]
if this is still happens please reopen an issue
