### ISSUE TITLE
[BUG] error when starting server

### ISSUE THREAD

**Issue by Everts0n** [Elytrium/LimboAuth#148]
**Describe the bug**
How to fix this error? Downloaded the latest version from here (github)
```
[18:23:18 ERROR]: Couldn't pass ProxyInitializeEvent to limboauth
java.lang.NoClassDefFoundError: com/velocitypowered/proxy/protocol/packet/ServerLogin
        at net.elytrium.limboauth.listener.AuthListener.<clinit>(AuthListener.java:176) ~[?:?]
        at net.elytrium.limboauth.LimboAuth.reload(LimboAuth.java:387) ~[?:?]
        at net.elytrium.limboauth.LimboAuth.onProxyInitialization(LimboAuth.java:208) ~[?:?]
        at net.elytrium.limboauth.Lmbda$3.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.3.0-SNAPSHOT (git-ecf936f3-b359)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity.jar:3.3.0-SNAPSHOT (git-ecf936f3-b359)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity.jar:3.3.0-SNAPSHOT (git-ecf936f3-b359)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.ClassNotFoundException: com.velocitypowered.proxy.protocol.packet.ServerLogin
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87) ~[velocity.jar:3.3.0-SNAPSHOT (git-ecf936f3-b359)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[velocity.jar:3.3.0-SNAPSHOT (git-ecf936f3-b359)]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 10 more
```

**Server Info (please complete the following information):**
```
{
  "versionInfo": {
    "name": "Velocity",
    "vendor": "Velocity Contributors",
    "version": "3.3.0-SNAPSHOT (git-ecf936f3-b359)"
  },
  "platform": {
    "operatingSystemType": "Linux",
    "operatingSystemVersion": "5.4.0-163-generic",
    "operatingSystemArchitecture": "amd64",
    "javaVersion": "17.0.10",
    "javaVendor": "Eclipse Adoptium",
    "listener": {
      "listenerType": "epoll",
      "compression": "libdeflate (Linux x86_64)",
      "encryption": "OpenSSL 3.0.x (Linux x86_64)"
    }
  },
  "config": {
    "bind": "0.0.0.0:25577",
    "motd": "\u003c#09add3\u003eA Velocity Server",
    "showMaxPlayers": 500,
    "onlineMode": true,
    "preventClientProxyConnections": false,
    "playerInfoForwardingMode": "NONE",
    "announceForge": false,
    "onlineModeKickExistingPlayers": false,
    "pingPassthrough": "DISABLED",
    "advanced": {
      "compressionThreshold": 256,
      "compressionLevel": -1,
      "loginRatelimit": 3000,
      "connectionTimeout": 5000,
      "readTimeout": 30000,
      "proxyProtocol": false,
      "tcpFastOpen": false,
      "bungeePluginMessageChannel": true,
      "showPingRequests": false,
      "failoverOnUnexpectedServerDisconnect": true,
      "announceProxyCommands": true,
      "logCommandExecutions": false,
      "logPlayerConnections": true
    },
    "query": {
      "queryEnabled": false,
      "queryPort": 25577,
      "queryMap": "Velocity",
      "showPlugins": false
    },
    "enablePlayerAddressLogging": true,
    "forceKeyAuthentication": true,
    "servers": {
      "minigames": {
        "currentPlayers": 0,
        "host": "127.0.0.1",
        "port": 30068
      },
      "lobby": {
        "currentPlayers": 0,
        "host": "127.0.0.1",
        "port": 30066
      },
      "factions": {
        "currentPlayers": 0,
        "host": "127.0.0.1",
        "port": 30067
      }
    },
    "connectOrder": [
      "lobby"
    ],
    "forcedHosts": {
      "minigames.example.com": [
        "minigames"
      ],
      "lobby.example.com": [
        "lobby"
      ],
      "factions.example.com": [
        "factions"
      ]
    }
  },
  "plugins": [
    {
      "id": "limboapi",
      "name": "LimboAPI",
      "version": "1.1.21",
      "authors": [
        "Elytrium (https://elytrium.net/)"
      ],
      "description": "Velocity plugin for making virtual servers.",
      "url": "https://elytrium.net/"
    },
    {
      "id": "limboauth",
      "name": "LimboAuth",
      "version": "1.1.13",
      "authors": [
        "Elytrium (https://elytrium.net/)"
      ],
      "url": "https://elytrium.net/",
      "dependencies": [
        "limboapi",
        "floodgate"
      ]
    },
    {
      "id": "limbofilter",
      "name": "LimboFilter",
      "version": "1.1.15",
      "authors": [
        "Elytrium (https://elytrium.net/)"
      ],
      "url": "https://elytrium.net/",
      "dependencies": [
        "limboapi"
      ]
    }
  ]
}
```

**Comment by DHCPCD9** [comment]
Use devbuild from modrinth
