### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by nsvk13** [Elytrium/LimboAuth#153]
LimboAuth не может прокси иницилизировать, хз, отображение голов в табе для лицензионных аккаунтов - не работает.
`[10:35:59] [Velocity Async Event Executor - #0/INFO] [limboapi]: Creating and preparing packets...
[10:35:59] [Velocity Async Event Executor - #0/INFO] [limboapi]: Loaded!
[10:36:02] [Velocity Async Event Executor - #0/ERROR] [com.velocitypowered.proxy.event.VelocityEventManager]: Couldn't pass ProxyInitializeEvent to limboauth
java.lang.NoClassDefFoundError: com/velocitypowered/proxy/protocol/packet/ServerLogin
  at net.elytrium.limboauth.listener.AuthListener.<clinit>(AuthListener.java:176) ~[?:?]
  at net.elytrium.limboauth.LimboAuth.reload(LimboAuth.java:387) ~[?:?]
  at net.elytrium.limboauth.LimboAuth.onProxyInitialization(LimboAuth.java:208) ~[?:?]
  at net.elytrium.limboauth.Lmbda$5.execute(Unknown Source) ~[?:?]
  at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
  at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
  at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
  at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.ClassNotFoundException: com.velocitypowered.proxy.protocol.packet.ServerLogin
  at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87) ~[velocity.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
  at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[velocity.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
  ... 10 more`

**Comment by nsvk13** [comment]
Velocity, 1.20.1

**Comment by SkyWatcher2019** [comment]
Скачай последний [девбилд](https://modrinth.com/plugin/limboauth/versions)
