### ISSUE TITLE
[BUG]  java.lang.NoClassDefFoundError: com/velocitypowered/proxy/protocol/packet/ServerLogin

### ISSUE THREAD

**Issue by iimrudy** [Elytrium/LimboAuth#164]
**Describe the bug**
limbo auth fails to load because of an NoClassDefFoundError

[14:06:36 ERROR]: Couldn't pass ProxyInitializeEvent to limboauth 1.1.13
java.lang.NoClassDefFoundError: com/velocitypowered/proxy/protocol/packet/ServerLogin
        at net.elytrium.limboauth.listener.AuthListener.<clinit>(AuthListener.java:176) ~[?:?]
        at net.elytrium.limboauth.LimboAuth.reload(LimboAuth.java:387) ~[?:?]
        at net.elytrium.limboauth.LimboAuth.onProxyInitialization(LimboAuth.java:208) ~[?:?]
        at net.elytrium.limboauth.Lmbda$3.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.3.0-SNAPSHOT-390.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity-3.3.0-SNAPSHOT-390.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity-3.3.0-SNAPSHOT-390.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ClassNotFoundException: com.velocitypowered.proxy.protocol.packet.ServerLogin
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87) ~[velocity-3.3.0-SNAPSHOT-390.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[velocity-3.3.0-SNAPSHOT-390.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 10 more
**To Reproduce**
just downloading latest version of Velocity, installing the plugins and running velocity

**Expected behavior**
limboauth should startup fine

**Server Info (please complete the following information):**
 - All Limbo plugins versions:
 - LimboAPI 1.1.23
 - LimboAuth 1.1.13

 - /velocity dump link [e.g. https://dump.velocitypowered.com/abcdef.json]
https://pastebin.com/vfkxisba

**Comment by SkyWatcher2019** [comment]
[Update](https://modrinth.com/plugin/limboauth/versions) LimboAuth

**Comment by iimrudy** [comment]
thank you for the fast reply, is the gradle repositoriesalso updated? also it would be good to add this link as link in the releases or in the repo good otherwise it would be misleading :)
