### ISSUE TITLE
[BUG] com.velocitypowered.proxy.connection.client.AuthSessionHandler

### ISSUE THREAD

**Issue by srlss123** [Elytrium/LimboAuth#27]
**Describe the bug**
A clear and concise description of the bug.

**To Reproduce**
1. Player join the game
3. See error

**Expected behavior**

**Screenshots**

**Server Info (please complete the following information):**
 - All Limbo plugins versions:
 - limboauth-1.0.3-jdk16.jar
 - [limboapi-plugin-1.0.3-jdk16.jar](https://github.com/Elytrium/LimboAPI/releases/download/1.0.3/limboapi-plugin-1.0.3-jdk16.jar)

/ - /velocity dump link [e.g. https://dump.velocitypowered.com/abcdef.json]

**Additional context**
[16:12:47 INFO] [limboapi]: likangxian1007 (/47.102.156.194:27683) has connected to the LimboAuth Limbo
[16:12:47 ERROR]: [initial connection] /47.102.156.194:27683: exception encountered in com.velocitypowered.proxy.connection.client.AuthSessionHandler@7999d319
io.netty.handler.codec.EncoderException: PreparedPacketEncoder must produce at least one message.
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:96) ~[velocity-3.1.2-SNAPSHOT-137.jar:3.1.2-SNAPSHOT (git-aa38d3e5-b137)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[velocity-3.1.2-SNAPSHOT-137.jar:3.1.2-SNAPSHOT (git-aa38d3e5-b137)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[velocity-3.1.2-SNAPSHOT-137.jar:3.1.2-SNAPSHOT (git-aa38d3e5-b137)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[velocity-3.1.2-SNAPSHOT-137.jar:3.1.2-SNAPSHOT (git-aa38d3e5-b137)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[velocity-3.1.2-SNAPSHOT-137.jar:3.1.2-SNAPSHOT (git-aa38d3e5-b137)]
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015) ~[velocity-3.1.2-SNAPSHOT-137.jar:3.1.2-SNAPSHOT (git-aa38d3e5-b137)]
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301) ~[velocity-3.1.2-SNAPSHOT-137.jar:3.1.2-SNAPSHOT (git-aa38d3e5-b137)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.delayedWrite(MinecraftConnection.java:230) ~[velocity-3.1.2-SNAPSHOT-137.jar:3.1.2-SNAPSHOT (git-aa38d3e5-b137)]
        at net.elytrium.limboapi.server.LimboImpl.lambda$spawnPlayer$4(LimboImpl.java:224) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[velocity-3.1.2-SNAPSHOT-137.jar:3.1.2-SNAPSHOT (git-aa38d3e5-b137)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[velocity-3.1.2-SNAPSHOT-137.jar:3.1.2-SNAPSHOT (git-aa38d3e5-b137)]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[velocity-3.1.2-SNAPSHOT-137.jar:3.1.2-SNAPSHOT (git-aa38d3e5-b137)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[velocity-3.1.2-SNAPSHOT-137.jar:3.1.2-SNAPSHOT (git-aa38d3e5-b137)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.1.2-SNAPSHOT-137.jar:3.1.2-SNAPSHOT (git-aa38d3e5-b137)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.1.2-SNAPSHOT-137.jar:3.1.2-SNAPSHOT (git-aa38d3e5-b137)]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[16:12:47 INFO] [limboapi]: likangxian1007 (/47.102.156.194:27683) has disconnected from the LimboAuth Limbo

**Comment by hevav** [comment]
1) If you need the support of Minecraft 1.18.2, please update to 1.0.4 LimboAPI and LimboAuth versions.
2) Check plugins/limboapi/config.yml for max and min prepare versions.

**Comment by mdxd44** [comment]
I assume the problem has already been fixed.
