### ISSUE TITLE
[BUG] Cross server transmission cannot be carried out for the first time, and / server cannot be used for cross server transmission

### ISSUE THREAD

**Issue by yuankun1** [Elytrium/LimboAuth#28]
1. Cross server transmission cannot be carried out for the first time, and / server cannot be used for cross server transmission
2. When I enter the server twice, I can carry out cross server transmission
3. limboauth-1.0.4-SNAPSHOT and limboapi-plugin-1.0.4-SNAPSHOT
4. The first time I can cross server or use / server
[23:22:19 ERROR]: [connected player] yuan_kun (/61.144.96.140:62915): unable to connect to server poke1
java.io.IOException: Unexpectedly disconnected from remote server
        at com.velocitypowered.proxy.connection.backend.TransitionSessionHandler.disconnected(TransitionSessionHandler.java:207) ~[velocity-3.1.2-SNAPSHOT-137.jar:3.1.2-SNAPSHOT (git-aa38d3e5-b137)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.channelInactive(MinecraftConnection.java:114) ~[velocity-3.1.2-SNAPSHOT-137.jar:3.1.2-SNAPSHOT (git-aa38d3e5-b137)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[velocity-3.1.2-SNAPSHOT-137.jar:3.1.2-SNAPSHOT (git-aa38d3e5-b137)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[velocity-3.1.2-SNAPSHOT-137.jar:3.1.2-SNAPSHOT (git-aa38d3e5-b137)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[velocity-3.1.2-SNAPSHOT-137.jar:3.1.2-SNAPSHOT (git-aa38d3e5-b137)]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) ~[velocity-3.1.2-SNAPSHOT-137.jar:3.1.2-SNAPSHOT (git-aa38d3e5-b137)]
        at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277) ~[velocity-3.1.2-SNAPSHOT-137.jar:3.1.2-SNAPSHOT (git-aa38d3e5-b137)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[velocity-3.1.2-SNAPSHOT-137.jar:3.1.2-SNAPSHOT (git-aa38d3e5-b137)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[velocity-3.1.2-SNAPSHOT-137.jar:3.1.2-SNAPSHOT (git-aa38d3e5-b137)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[velocity-3.1.2-SNAPSHOT-137.jar:3.1.2-SNAPSHOT (git-aa38d3e5-b137)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:392) ~[velocity-3.1.2-SNAPSHOT-137.jar:3.1.2-SNAPSHOT (git-aa38d3e5-b137)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:357) ~[velocity-3.1.2-SNAPSHOT-137.jar:3.1.2-SNAPSHOT (git-aa38d3e5-b137)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[velocity-3.1.2-SNAPSHOT-137.jar:3.1.2-SNAPSHOT (git-aa38d3e5-b137)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[velocity-3.1.2-SNAPSHOT-137.jar:3.1.2-SNAPSHOT (git-aa38d3e5-b137)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[velocity-3.1.2-SNAPSHOT-137.jar:3.1.2-SNAPSHOT (git-aa38d3e5-b137)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405) ~[velocity-3.1.2-SNAPSHOT-137.jar:3.1.2-SNAPSHOT (git-aa38d3e5-b137)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[velocity-3.1.2-SNAPSHOT-137.jar:3.1.2-SNAPSHOT (git-aa38d3e5-b137)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[velocity-3.1.2-SNAPSHOT-137.jar:3.1.2-SNAPSHOT (git-aa38d3e5-b137)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901) ~[velocity-3.1.2-SNAPSHOT-137.jar:3.1.2-SNAPSHOT (git-aa38d3e5-b137)]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813) ~[velocity-3.1.2-SNAPSHOT-137.jar:3.1.2-SNAPSHOT (git-aa38d3e5-b137)]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[velocity-3.1.2-SNAPSHOT-137.jar:3.1.2-SNAPSHOT (git-aa38d3e5-b137)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[velocity-3.1.2-SNAPSHOT-137.jar:3.1.2-SNAPSHOT (git-aa38d3e5-b137)]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[velocity-3.1.2-SNAPSHOT-137.jar:3.1.2-SNAPSHOT (git-aa38d3e5-b137)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[velocity-3.1.2-SNAPSHOT-137.jar:3.1.2-SNAPSHOT (git-aa38d3e5-b137)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.1.2-SNAPSHOT-137.jar:3.1.2-SNAPSHOT (git-aa38d3e5-b137)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.1.2-SNAPSHOT-137.jar:3.1.2-SNAPSHOT (git-aa38d3e5-b137)]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by hevav** [comment]
Are you sure that this is the LimboAPI/LimboAuth issue?
