### ISSUE TITLE
help [BUG] 

### ISSUE THREAD

**Issue by zeonmomentx** [Elytrium/LimboAuth#36]
Couldn't pass ProxyInitializeEvent to limboauth
java.lang.IllegalStateException: If you want floodgate players to automatically pass auth (floodgate-need-auth: false), please install floodgate plugin.
        at net.elytrium.limboauth.LimboAuth.reload(LimboAuth.java:207) ~[?:?]
        at net.elytrium.limboauth.LimboAuth.onProxyInitialization(LimboAuth.java:182) ~[?:?]
        at net.elytrium.limboauth.Lmbda$3.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[server.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[server.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[server.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

what can i do?

**Comment by SkyWatcher2019** [comment]
read the 1st line of error

**Comment by zeonmomentx** [comment]
i have off server
