### ISSUE TITLE
[BUG] Error and warnings

### ISSUE THREAD

**Issue by SnonSS** [Elytrium/LimboAuth#66]
[14:58:37 WARN] [io.netty.util.concurrent.AbstractEventExecutor]: A task raised an exception. Task: net.elytrium.limboauth.listener.AuthListener$$Lambda$1253/0x000000080119b6e8@2c6332f0
net.elytrium.limboauth.model.SQLRuntimeException: An unexpected internal error was caught during the database SQL operations.
        at net.elytrium.limboauth.handler.AuthSessionHandler.fetchInfo(AuthSessionHandler.java:490) ~[?:?]
        at net.elytrium.limboauth.LimboAuth.authPlayer(LimboAuth.java:536) ~[?:?]
        at net.elytrium.limboauth.listener.AuthListener.lambda$onLoginLimboRegister$1(AuthListener.java:120) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[server.jar:3.2.0-SNAPSHOT (git-8a048f05-b220)]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[server.jar:3.2.0-SNAPSHOT (git-8a048f05-b220)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[server.jar:3.2.0-SNAPSHOT (git-8a048f05-b220)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[server.jar:3.2.0-SNAPSHOT (git-8a048f05-b220)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[server.jar:3.2.0-SNAPSHOT (git-8a048f05-b220)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:3.2.0-SNAPSHOT (git-8a048f05-b220)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[server.jar:3.2.0-SNAPSHOT (git-8a048f05-b220)]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: The last packet successfully received from the server was 72,068,165 milliseconds ago. The last packet sent successfully to the server was 72,068,206 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
        at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) ~[?:?]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[?:?]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916) ~[?:?]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:972) ~[?:?]
        at net.elytrium.limboauth.thirdparty.com.j256.ormlite.jdbc.JdbcCompiledStatement.runQuery(JdbcCompiledStatement.java:65) ~[?:?]
        at net.elytrium.limboauth.thirdparty.com.j256.ormlite.stmt.SelectIterator.<init>(SelectIterator.java:55) ~[?:?]
        at net.elytrium.limboauth.thirdparty.com.j256.ormlite.stmt.StatementExecutor.buildIterator(StatementExecutor.java:253) ~[?:?]
        at net.elytrium.limboauth.thirdparty.com.j256.ormlite.stmt.StatementExecutor.query(StatementExecutor.java:202) ~[?:?]
        at net.elytrium.limboauth.thirdparty.com.j256.ormlite.dao.BaseDaoImpl.query(BaseDaoImpl.java:286) ~[?:?]
        at net.elytrium.limboauth.thirdparty.com.j256.ormlite.stmt.QueryBuilder.query(QueryBuilder.java:384) ~[?:?]
        at net.elytrium.limboauth.thirdparty.com.j256.ormlite.stmt.Where.query(Where.java:519) ~[?:?]
        at net.elytrium.limboauth.thirdparty.com.j256.ormlite.dao.BaseDaoImpl.queryForEq(BaseDaoImpl.java:262) ~[?:?]
        at net.elytrium.limboauth.handler.AuthSessionHandler.fetchInfo(AuthSessionHandler.java:487) ~[?:?]
        ... 10 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: The last packet successfully received from the server was 72,068,165 milliseconds ago. The last packet sent successfully to the server was 72,068,206 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[?:?]
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[?:?]
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[?:?]
        at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167) ~[?:?]
        at com.mysql.cj.protocol.a.NativeProtocol.send(NativeProtocol.java:628) ~[?:?]
        at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:683) ~[?:?]
        at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1051) ~[?:?]
        at com.mysql.cj.NativeSession.execSQL(NativeSession.java:665) ~[?:?]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:893) ~[?:?]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:972) ~[?:?]
        at net.elytrium.limboauth.thirdparty.com.j256.ormlite.jdbc.JdbcCompiledStatement.runQuery(JdbcCompiledStatement.java:65) ~[?:?]
        at net.elytrium.limboauth.thirdparty.com.j256.ormlite.stmt.SelectIterator.<init>(SelectIterator.java:55) ~[?:?]
        at net.elytrium.limboauth.thirdparty.com.j256.ormlite.stmt.StatementExecutor.buildIterator(StatementExecutor.java:253) ~[?:?]
        at net.elytrium.limboauth.thirdparty.com.j256.ormlite.stmt.StatementExecutor.query(StatementExecutor.java:202) ~[?:?]
        at net.elytrium.limboauth.thirdparty.com.j256.ormlite.dao.BaseDaoImpl.query(BaseDaoImpl.java:286) ~[?:?]
        at net.elytrium.limboauth.thirdparty.com.j256.ormlite.stmt.QueryBuilder.query(QueryBuilder.java:384) ~[?:?]
        at net.elytrium.limboauth.thirdparty.com.j256.ormlite.stmt.Where.query(Where.java:519) ~[?:?]
        at net.elytrium.limboauth.thirdparty.com.j256.ormlite.dao.BaseDaoImpl.queryForEq(BaseDaoImpl.java:262) ~[?:?]
        at net.elytrium.limboauth.handler.AuthSessionHandler.fetchInfo(AuthSessionHandler.java:487) ~[?:?]
        ... 10 more
Caused by: java.net.SocketException: Connection reset by peer
        at sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:420) ~[?:?]
        at sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:440) ~[?:?]
        at sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:826) ~[?:?]
        at java.net.Socket$SocketOutputStream.write(Socket.java:1035) ~[?:?]
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81) ~[?:?]
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142) ~[?:?]
        at com.mysql.cj.protocol.a.SimplePacketSender.send(SimplePacketSender.java:55) ~[?:?]
        at com.mysql.cj.protocol.a.TimeTrackingPacketSender.send(TimeTrackingPacketSender.java:50) ~[?:?]
        at com.mysql.cj.protocol.a.NativeProtocol.send(NativeProtocol.java:619) ~[?:?]
        at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:683) ~[?:?]
        at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1051) ~[?:?]
        at com.mysql.cj.NativeSession.execSQL(NativeSession.java:665) ~[?:?]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:893) ~[?:?]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:972) ~[?:?]
        at net.elytrium.limboauth.thirdparty.com.j256.ormlite.jdbc.JdbcCompiledStatement.runQuery(JdbcCompiledStatement.java:65) ~[?:?]
        at net.elytrium.limboauth.thirdparty.com.j256.ormlite.stmt.SelectIterator.<init>(SelectIterator.java:55) ~[?:?]
        at net.elytrium.limboauth.thirdparty.com.j256.ormlite.stmt.StatementExecutor.buildIterator(StatementExecutor.java:253) ~[?:?]
        at net.elytrium.limboauth.thirdparty.com.j256.ormlite.stmt.StatementExecutor.query(StatementExecutor.java:202) ~[?:?]
        at net.elytrium.limboauth.thirdparty.com.j256.ormlite.dao.BaseDaoImpl.query(BaseDaoImpl.java:286) ~[?:?]
        at net.elytrium.limboauth.thirdparty.com.j256.ormlite.stmt.QueryBuilder.query(QueryBuilder.java:384) ~[?:?]
        at net.elytrium.limboauth.thirdparty.com.j256.ormlite.stmt.Where.query(Where.java:519) ~[?:?]
        at net.elytrium.limboauth.thirdparty.com.j256.ormlite.dao.BaseDaoImpl.queryForEq(BaseDaoImpl.java:262) ~[?:?]
        at net.elytrium.limboauth.handler.AuthSessionHandler.fetchInfo(AuthSessionHandler.java:487) ~[?:?]
        ... 10 more

**Comment by hevav** [comment]
> The last packet successfully received from the server was 72,068,165 milliseconds ago. The last packet sent successfully to the server was 72,068,206 milliseconds ago.

@SnonSS Your database server isn't responding. This is an issue with your database
