### ISSUE TITLE
[BUG] Help, Couldn't pass ProxyInitializeEvent to limboauth

### ISSUE THREAD

**Issue by Klop233** [Elytrium/LimboAuth#68]
**Describe the bug**
`Couldn't pass ProxyInitializeEvent to limboauth` on startup and LimboAuth seems to not enable, I directly goes into the default server when I join

**To Reproduce**
1. Normally install it and start

**Screenshots**

**Server Info (please complete the following information):**
 - All Limbo plugins versions:
 - LimboAPI 1.1.0, from github release
 - LimboAuth 1.1.1, from github release

```
{
  "versionInfo": {
    "name": "Velocity",
    "vendor": "Velocity Contributors",
    "version": "3.2.0-SNAPSHOT (git-8a048f05-b220)"
  },
  "platform": {
    "operatingSystemType": "Linux",
    "operatingSystemVersion": "3.10.0-957.el7.x86_64",
    "operatingSystemArchitecture": "amd64",
    "javaVersion": "17.0.5",
    "javaVendor": "Alibaba",
    "listener": {
      "listenerType": "epoll",
      "compression": "libdeflate (Linux x86_64)",
      "encryption": "OpenSSL 1.0.x (Linux x86_64)"
    }
  },
  "config": {
    "bind": "0.0.0.0:25565",
    "motd": "\u0026#09add3A Velocity Server",
    "showMaxPlayers": 500,
    "onlineMode": false,
    "preventClientProxyConnections": false,
    "playerInfoForwardingMode": "MODERN",
    "announceForge": false,
    "onlineModeKickExistingPlayers": false,
    "pingPassthrough": "DISABLED",
    "advanced": {
      "compressionThreshold": 256,
      "compressionLevel": -1,
      "loginRatelimit": 3000,
      "connectionTimeout": 5000,
      "readTimeout": 30000,
      "proxyProtocol": false,
      "tcpFastOpen": true,
      "bungeePluginMessageChannel": true,
      "showPingRequests": false,
      "failoverOnUnexpectedServerDisconnect": true,
      "announceProxyCommands": true,
      "logCommandExecutions": true,
      "logPlayerConnections": true
    },
    "query": {
      "queryEnabled": false,
      "queryPort": 25577,
      "queryMap": "Velocity",
      "showPlugins": false
    },
    "enablePlayerAddressLogging": true,
    "forceKeyAuthentication": true,
    "servers": {
      "lobby": {
        "currentPlayers": 1,
        "host": "127.0.0.1",
        "port": 1040
      },
      "main": {
        "currentPlayers": 0,
        "host": "127.0.0.1",
        "port": 1001
      }
    },
    "connectOrder": [
      "lobby"
    ],
    "forcedHosts": {
      "lobby.example.com": [
        "lobby"
      ]
    }
  },
  "plugins": [
    {
      "id": "limboapi",
      "name": "LimboAPI",
      "version": "1.1.0",
      "authors": [
        "Elytrium (https://elytrium.net/)"
      ],
      "description": "Velocity plugin for making virtual servers.",
      "url": "https://elytrium.net/"
    },
    {
      "id": "limboauth",
      "name": "LimboAuth",
      "version": "1.1.1",
      "authors": [
        "Elytrium (https://elytrium.net/)"
      ],
      "url": "https://elytrium.net/",
      "dependencies": [
        "limboapi",
        "floodgate"
      ]
    }
  ]
}
```

**Velocity logs**
```
[21:53:01 INFO]: Booting up Velocity 3.2.0-SNAPSHOT (git-8a048f05-b220)...
[21:53:01 INFO]: Loading localizations...
[21:53:01 INFO]: Connections will use epoll channels, libdeflate (Linux x86_64) compression, OpenSSL 1.0.x (Linux x86_64) ciphers
[21:53:01 WARN]: The proxy is running in offline mode! This is a security risk and you will NOT receive any support!
[21:53:01 INFO]: Loading plugins...
[21:53:01 INFO] [limboapi]: Initializing Simple Virtual Block system...
[21:53:02 INFO] [limboapi]: Initializing Simple Virtual Item system...
[21:53:02 INFO] [limboapi]: Hooking into EventManager, PlayerList/UpsertPlayerInfo and StateRegistry...
[21:53:02 INFO]: Loaded plugin limboapi 1.1.0 by Elytrium (https://elytrium.net/)
[21:53:02 INFO]: Loaded plugin limboauth 1.1.1 by Elytrium (https://elytrium.net/)
[21:53:02 INFO]: Loaded 2 plugins
[21:53:02 INFO] [limboapi]: Creating and preparing packets...
[21:53:02 INFO] [limboapi]: Loaded!
[21:53:02 ERROR]: Couldn't pass ProxyInitializeEvent to limboauth
net.elytrium.commons.utils.reflection.ReflectionException: An unexpected internal error was caught during the reflection operations.
        at net.elytrium.limboauth.LimboAuth.reload(LimboAuth.java:306) ~[?:?]
        at net.elytrium.limboauth.LimboAuth.onProxyInitialization(LimboAuth.java:208) ~[?:?]
        at net.elytrium.limboauth.Lmbda$3.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[proxy.jar:3.2.0-SNAPSHOT (git-8a048f05-b220)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[proxy.jar:3.2.0-SNAPSHOT (git-8a048f05-b220)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[proxy.jar:3.2.0-SNAPSHOT (git-8a048f05-b220)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.h2.Driver
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87) ~[proxy.jar:3.2.0-SNAPSHOT (git-8a048f05-b220)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[proxy.jar:3.2.0-SNAPSHOT (git-8a048f05-b220)]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.lambda$static$2(DatabaseLibrary.java:45) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.connect(DatabaseLibrary.java:108) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.connectToORM(DatabaseLibrary.java:124) ~[?:?]
        at net.elytrium.limboauth.LimboAuth.reload(LimboAuth.java:298) ~[?:?]
        ... 8 more
[21:53:02 INFO]: Listening on /[0:0:0:0:0:0:0:0%0]:25565
[21:53:02 INFO]: Done (2.1s)!
[21:53:07 INFO]: [server connection] Klop233 -> lobby has connected
```

**Comment by hevav** [comment]
@Klop233 Can you tell me the names and sizes of the files located in directory ``libraries/com/h2database/h2/``?

**Comment by Klop233** [comment]
![image](https://user-images.githubusercontent.com/62453589/212698131-92089f0b-55ce-4a0a-824d-ed3bf0997b75.png)

**Comment by hevav** [comment]
@Klop233 Try deleting this file

**Comment by hevav** [comment]
Thank you for explaining the reason, we will re-implement the dependencies download so that this doesn't happen

**Comment by WhiteTigerSkyLands** [comment]
Help, the same error, the previous solution does not help, only the filter works, authorization does not work

**Comment by Cyanoure** [comment]
Same thing. Just installed a clear velocity server with LimboAPI, LimboFilter and LimboAuth. Nothing special.

**Comment by Cyanoure** [comment]
It works with the latest build: https://github.com/Elytrium/LimboAuth/actions/runs/7670771184

**Comment by Cyanoure** [comment]
Swithced to mysql, works just fine. Added few plugins, similar error. Deleted those plugins, same error again. Deleted the entire libraries folder, same error.
```
[17:11:29 ERROR]: Couldn't pass ProxyInitializeEvent to limboauth
net.elytrium.commons.utils.reflection.ReflectionException: An unexpected internal error was caught during the reflection operations.
        at net.elytrium.limboauth.LimboAuth.reload(LimboAuth.java:314) ~[?:?]
        at net.elytrium.limboauth.LimboAuth.onProxyInitialization(LimboAuth.java:212) ~[?:?]
        at net.elytrium.limboauth.Lmbda$3.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.3.0-SNAPSHOT (git-75d6dcc1-b371)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity.jar:3.3.0-SNAPSHOT (git-75d6dcc1-b371)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity.jar:3.3.0-SNAPSHOT (git-75d6dcc1-b371)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.fromDriver(DatabaseLibrary.java:161) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.lambda$static$4(DatabaseLibrary.java:74) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.connect(DatabaseLibrary.java:118) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.connectToORM(DatabaseLibrary.java:134) ~[?:?]
        at net.elytrium.limboauth.LimboAuth.reload(LimboAuth.java:306) ~[?:?]
        ... 8 more
Caused by: java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:111) ~[?:?]
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:98) ~[?:?]
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:90) ~[?:?]
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:64) ~[?:?]
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:74) ~[?:?]
        at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:895) ~[?:?]
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:820) ~[?:?]
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:446) ~[?:?]
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239) ~[?:?]
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188) ~[?:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.fromDriver(DatabaseLibrary.java:161) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.lambda$static$4(DatabaseLibrary.java:74) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.connect(DatabaseLibrary.java:118) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.connectToORM(DatabaseLibrary.java:134) ~[?:?]
        at net.elytrium.limboauth.LimboAuth.reload(LimboAuth.java:306) ~[?:?]
        ... 8 more
Caused by: com.mysql.cj.exceptions.CJException: Public Key Retrieval is not allowed
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62) ~[?:?]
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[?:?]
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:150) ~[?:?]
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:123) ~[?:?]
        at com.mysql.cj.protocol.a.authentication.CachingSha2PasswordPlugin.nextAuthenticationStep(CachingSha2PasswordPlugin.java:153) ~[?:?]
        at com.mysql.cj.protocol.a.authentication.CachingSha2PasswordPlugin.nextAuthenticationStep(CachingSha2PasswordPlugin.java:49) ~[?:?]
        at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:443) ~[?:?]
        at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:213) ~[?:?]
        at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1430) ~[?:?]
        at com.mysql.cj.NativeSession.connect(NativeSession.java:134) ~[?:?]
        at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:839) ~[?:?]
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:820) ~[?:?]
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:446) ~[?:?]
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239) ~[?:?]
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188) ~[?:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.fromDriver(DatabaseLibrary.java:161) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.lambda$static$4(DatabaseLibrary.java:74) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.connect(DatabaseLibrary.java:118) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.connectToORM(DatabaseLibrary.java:134) ~[?:?]
        at net.elytrium.limboauth.LimboAuth.reload(LimboAuth.java:306) ~[?:?]
        ... 8 more
Caused by: com.mysql.cj.exceptions.UnableToConnectException: Public Key Retrieval is not allowed
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62) ~[?:?]
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:86) ~[?:?]
        at com.mysql.cj.protocol.a.authentication.CachingSha2PasswordPlugin.nextAuthenticationStep(CachingSha2PasswordPlugin.java:130) ~[?:?]
        at com.mysql.cj.protocol.a.authentication.CachingSha2PasswordPlugin.nextAuthenticationStep(CachingSha2PasswordPlugin.java:49) ~[?:?]
        at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:443) ~[?:?]
        at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:213) ~[?:?]
        at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1430) ~[?:?]
        at com.mysql.cj.NativeSession.connect(NativeSession.java:134) ~[?:?]
        at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:839) ~[?:?]
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:820) ~[?:?]
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:446) ~[?:?]
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239) ~[?:?]
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188) ~[?:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.fromDriver(DatabaseLibrary.java:161) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.lambda$static$4(DatabaseLibrary.java:74) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.connect(DatabaseLibrary.java:118) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.connectToORM(DatabaseLibrary.java:134) ~[?:?]
        at net.elytrium.limboauth.LimboAuth.reload(LimboAuth.java:306) ~[?:?]
        ... 8 more
```

**Comment by Klop233** [comment]
```
D:\velocity>java -jar server.jar
[13:49:31 INFO]: Booting up Velocity 3.3.0-SNAPSHOT (git-75d6dcc1-b371)...
[13:49:31 INFO]: Loading localizations...
[13:49:31 INFO]: Connections will use NIO channels, Java compression, Java ciphers
[13:49:32 WARN]: The proxy is running in offline mode! This is a security risk and you will NOT receive any support!
[13:49:32 INFO]: Loading plugins...
[13:49:32 INFO] [limboapi]: Initializing Simple Virtual World system...
[13:49:33 INFO] [limboapi]: Hooking into EventManager, PlayerList/UpsertPlayerInfo and StateRegistry...
[13:49:33 INFO]: Loaded plugin limboapi 1.1.22 by Elytrium (https://elytrium.net/)
[13:49:33 INFO]: Loaded plugin limboauth 1.1.13 by Elytrium (https://elytrium.net/)
[13:49:33 INFO]: Loaded 2 plugins
[13:49:33 INFO] [limboapi]: Creating and preparing packets...
[13:49:33 INFO] [limboapi]: Loaded!
[13:49:36 ERROR]: Couldn't pass ProxyInitializeEvent to limboauth
java.lang.NoClassDefFoundError: com/velocitypowered/proxy/protocol/packet/ServerLogin
        at net.elytrium.limboauth.listener.AuthListener.<clinit>(AuthListener.java:176) ~[?:?]
        at net.elytrium.limboauth.LimboAuth.reload(LimboAuth.java:387) ~[?:?]
        at net.elytrium.limboauth.LimboAuth.onProxyInitialization(LimboAuth.java:208) ~[?:?]
        at net.elytrium.limboauth.Lmbda$3.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[server.jar:3.3.0-SNAPSHOT (git-75d6dcc1-b371)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[server.jar:3.3.0-SNAPSHOT (git-75d6dcc1-b371)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[server.jar:3.3.0-SNAPSHOT (git-75d6dcc1-b371)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:842) [?:?]
Caused by: java.lang.ClassNotFoundException: com.velocitypowered.proxy.protocol.packet.ServerLogin
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87) ~[server.jar:3.3.0-SNAPSHOT (git-75d6dcc1-b371)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[server.jar:3.3.0-SNAPSHOT (git-75d6dcc1-b371)]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 10 more
[13:49:36 INFO]: Listening on /[0:0:0:0:0:0:0:0]:25565
[13:49:36 INFO]: Done (5.28s)!
```

I tried many times and got the same error.

**Comment by Andronchikchik** [comment]
I have the same error
[22:44:39 ERROR]: Couldn't pass ProxyInitializeEvent to limboauth 1.1.13
java.lang.NoClassDefFoundError: com/velocitypowered/proxy/protocol/packet/ServerLogin
        at net.elytrium.limboauth.listener.AuthListener.<clinit>(AuthListener.java:176) ~[?:?]
        at net.elytrium.limboauth.LimboAuth.reload(LimboAuth.java:387) ~[?:?]
        at net.elytrium.limboauth.LimboAuth.onProxyInitialization(LimboAuth.java:208) ~[?:?]
        at net.elytrium.limboauth.Lmbda$3.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.3.0-SNAPSHOT (git-a72aef52-b375)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.3.0-SNAPSHOT (git-a72aef52-b375)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.3.0-SNAPSHOT (git-a72aef52-b375)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ClassNotFoundException: com.velocitypowered.proxy.protocol.packet.ServerLogin
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87) ~[velocity.jar:3.3.0-SNAPSHOT (git-a72aef52-b375)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[velocity.jar:3.3.0-SNAPSHOT (git-a72aef52-b375)]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 10 more
        
        The main question is how to solve this?
        
        (русс)
        
        у меня таже ошибка, как это решить?

**Comment by szarkans** [comment]
У кого такая проблема - проверьте права доступа своего аккаунта на VDS. У меня была такая же ошибка, т.к. не выдал достаточно прав

**Comment by HowieHz** [comment]
I ran into this issue today when upgrading plugins and velocity, suggesting joining the upgrade guide.
**Delete libraries/com/h2database/h2/  folder when you are upgrading the plugin**
@hevav

**Comment by ssgameing5678** [comment]
same problem PLEASE HELP

**Comment by ssgameing5678** [comment]
[12:46:49 ERROR]: Couldn't pass ProxyInitializeEvent to limboapi 1.1.27-SNAPSHOT (git-f779f2d)
